export const userData = [
  {
    title: "Dance Battle",
    japaneseName: "Ronin Rhythm",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415730/2.jpg_nn3xcx.jpg",
    category: "Mega",
    overview: "Individual head-to-head dance battles with changing music genres in a knockout format leading to a Final Showdown.",
    day: 1,
    time: "12:30PM - 4:00PM",
    venue: "Badminton Court",
    rules: [
      "Individual participations only.",
      "Each battle features two dancers facing off in a head-to-head challenge.",
      "Battle Format: Each round, the music genre changes unpredictably. Possible styles include Rap, Pop, Break beats, Funk, Electronica, House, Bollywood etc.",
      "Time per dancer: 45–60 seconds to showcase their moves before the opponent responds.",
      "Battles are conducted in a knockout format, leading to a Final Showdown.",
      "Judges select one dancer from each battle to advance to the next round.",
      "The knockout rounds continue until only two dancers remain for the final showdown.",
      "Final Showdown: The last two dancers compete in multiple rounds with surprise music transitions.",
    ],
    rounds: [],
    criteria: ["Artistic Creativity", "Musicality & Rhythm Adaptation", "Stage Presence & Confidence", "Crowd Engagement", "Overall Entertainment Value"],
  },
  {
    title: "Group Dance",
    japaneseName: "Odori Matsuri",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415730/4.jpg_eynb1h.jpg",
    category: "Mega",
    overview: "Team-based dance performance event showcasing creativity and versatility in Eastern and Western styles.",
    day: 2,
    time: "11:30AM - 1:30PM",
    venue: "Auditorium",
    rules: [
      "Teams must consist of a minimum of 4 and a maximum of 15 members.", "All members of the team should individually register for the event" ,
      "Performance duration: 5+2 minutes (including stage setup and clearance).",
      "Dance styles encompass both Eastern and Western forms without separate categories.",
      "Teams must showcase their creativity and versatility within the given time frame.",
      "Use of props is allowed but should not cause stage damage.",
      "Any form of inappropriate content or offensive gestures will lead to disqualification.",
    ],
    rounds: [],
    criteria: ["Expressions", "Choreography", "Synchronization & Impact", "Costumes"],
  },
  {
    title: "Mr or Ms Envision",
    japaneseName: "Mr or Ms Sakura Crown",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415732/6.jpg_e5csnj.jpg",
    category: "Mega",
    overview: "Individual personality competition testing aptitude, public speaking and composure under stress.",
    day: 1,
    time: "1:00PM - 2:00PM",
    venue: "003",
    rules: [
      "Individual participations only.",
      "Teams must report 30 minutes before their performance.",
      "Exceeding time limits may result in point deduction.",
    ],
    rounds: [
      { roundNumber: 1, name: "Aptitude Test", format: "Written test on logical reasoning, analytical skills, basic problem-solving.", evaluation: "Top performers qualify for Round 2.", duration: "30 minutes" },
      { roundNumber: 2, name: "Effective Public Speaking", format: "Spontaneous topic given on the spot; must deliver a structured speech without prior preparation.", evaluation: "Clarity and fluency, Confidence and stage presence, Relevance and strength of content.", duration: "2 minutes per participant" },
      { roundNumber: 3, name: "Stress Interview", format: "Participants dress as a chosen character; judges ask situational and character-based questions.", evaluation: "Creativity and spontaneity, Presence of mind, Ability to handle stress effectively.", duration: "5–7 minutes per participant" },
    ],
    criteria: ["Aptitude Test: Problem-solving ability and logical reasoning", "Public Speaking: Clarity, fluency and confidence", "Stress Interview: Creativity, presence of mind and ability to handle pressure"],
  },
  {
    title: "Singing",
    japaneseName: "Samurai Symphony",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415732/8.jpg_vcetxc.jpg",
    category: "Mega",
    overview: "A multi-round singing competition open to individual participants, evaluating voice quality, expression and style.",
    day: 1,
    time: "10:00AM - 12:00PM",
    venue: "Seminar Hall",
    rules: [
      "All registered participants are eligible to perform in Round 1.",
      "Individual participations only.",
      "Participants can sing any song of their choice in any language in Round 1.",
      "Karaoke track is allowed, but singing without a track is also permitted.",
      "Participants must report 30 minutes before their performance.",
      "Exceeding time limits may result in point deduction.",
    ],
    rounds: [
      { roundNumber: 1, name: "Open Singing Round", format: "Theme: Free Choice. Any song in any language. Karaoke allowed.", evaluation: "Voice quality, pitch, rhythm and stage confidence.", duration: "3+1 minutes per participant" },
      { roundNumber: 2, name: "Expression Round", format: "Theme: Emotion & Style. Song must express emotion; facial expressions and gestures allowed.", evaluation: "Expression, creativity and overall performance style.", duration: "2+1 minutes" },
    ],
    criteria: ["Voice quality", "Pitch and rhythm", "Stage confidence", "Expression and creativity"],
  },
  {
    title: "Cricket",
    japaneseName: "Dojo Dominators",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415732/10.jpg_l5wwnq.jpg",
    category: "Mega",
    overview: "Knockout format cricket tournament with 8-player teams and short 2–3 over matches.",
    day: 1,
    time: "10:00 AM",
    venue: "Ground",
    rules: [
      "Match Format: Knockout matches : 2–3 overs per side depending on registration.",
      "All members of the team should individually register for the event" ,
      "Each team shall consist of 8 players.",
      "Overs & Bowling Rule (1-1-1): Each bowler can bowl only 1 over.",
      "All 8 players can bat. If 7 wickets fall, last batter may not continue.",
      "Boundary will be marked within 30 yards.",
      "Wide and No-ball will give 1 extra run + extra ball.",
      "The umpire's decision is final and binding.",
      "In case of tie: Super Over (1 over each); Higher boundary count if Super Over not possible.",
      "Misconduct or arguments with umpire may lead to disqualification.",
    ],
    rounds: [],
    criteria: [],
  },
  {
    title: "Rahasya",
    japaneseName: "Kage Investigation",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415734/13.jpg_l1bvny.jpg",
    category: "Technical",
    overview: "A team-based competitive investigation event testing teamwork, analytical skills, and adherence to competition guidelines.",
    day: 2,
    time: "11:00AM - 12:00 AM",
    venue: "AIML LAB",
    rules: [
      "Participation is strictly in teams of 3–4 members.",
      "All members of the team should individually register for the event" ,
      "Each team is allowed to use only one laptop or desktop.",
      "Total Duration: 2 Hours 20 Minutes (Briefing: 15 min, Investigation Rounds: 1 hr 45 min, Extra Time: 20 min).",
      "No external internet usage is allowed unless explicitly permitted by the organizers.",
      "Only approved tools and software may be used during the event.",
      "Tampering with event materials or setup is strictly prohibited.",
      "No communication between teams is allowed during the competition.",
      "Any form of misconduct will result in immediate disqualification.",
      "The decision of the organizers will be final and binding.",
    ],
    rounds: [],
    criteria: [],
  },
  {
    title: "Blind Coding",
    japaneseName: "Kizuna Code",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415734/15.jpg_mrjd9y.jpg",
    category: "Technical",
    overview: "A collaborative coding challenge where one participant writes code while the other guides verbally without visual access to the screen.",
    day: 1,
    time: "2:00PM - 3:00PM",
    venue: "AIDS lab",
    rules: [
      "Participation is strictly in teams of 2 members",
      "All members of the team should individually register for the event" ,
      "Players will sit opposite each other during the competition.",
      "One player acts as the Coder (sees screen and types); the other is the Guide (dictates logic without seeing the screen).",
      "The Guide must not touch the keyboard, mouse or screen at any time.",
      "No gestures, signs, written notes or non-verbal assistance are allowed.",
      "The programming language will be announced before the event begins.",
      "Code must be written strictly according to the given problem statement.",
      "Any violation of rules will result in immediate disqualification.",
    ],
    rounds: [],
    criteria: ["Correctness of the code", "Adherence to instructions", "Successful execution within the time limit"],
  },
  {
    title: "Reverse Coding",
    japaneseName: "Shinobi Syntax",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415733/17.jpg_mjezez.jpg",
    category: "Technical",
    overview: "A technical coding competition where participants analyse a given output and reconstruct the logic to match it.",
    day: 2,
    time: "9:30AM - 11:00AM",
    venue: "ISE LAB",
    rules: [
      "Participants may register individually or in a team of maximum 2 members.",
      "Both rounds will strictly follow the Reverse Coding format.",
      "Internet access is strictly prohibited during the competition.",
      "Use of mobile phones, AI tools, online resources or external assistance is not allowed.",
      "Any form of malpractice will lead to immediate disqualification.",
      "No refunds will be provided after payment.",
    ],
    rounds: [
      { roundNumber: 1, name: "Reverse Coding – C Programming", format: "Analyse the provided output and implement the logic strictly using C.", evaluation: "Exact output match including formatting, spacing and structure.", duration: null },
      { roundNumber: 2, name: "Reverse Coding – Python Programming", format: "Analyse the provided output and implement the logic strictly using Python.", evaluation: "Exact output match including formatting, spacing and structure.", duration: null },
    ],
    criteria: [],
  },
  {
    title: "Operation Cipher Chase",
    japaneseName: "Cipher Shinobi",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415734/19.jpg_hep6q3.jpg",
    category: "Technical",
    overview: "A team-based technical treasure hunt where participants solve multi-level challenges by identifying hidden clues within a system and at designated physical locations.",
    day: 2,
    time: "10:30AM - 11:30AM",
    venue: "CS LAB",
    rules: [
      "The event will be conducted in teams of 2–3 participants.",
     "All members of the team should individually register for the event" ,
      "Participants must explore only authorized areas.",
      "Internet access and external devices are strictly prohibited unless permitted by the organizers.",
      "Participants must not alter system settings, delete files, or access restricted system areas.",
      "Any form of unfair means or clue sharing between teams will lead to immediate disqualification.",
      "No refunds will be provided after payment.",
    ],
    rounds: [
      { roundNumber: 1, name: "System Exploration", format: "Teams analyse the provided system to locate hidden digital clues without altering system settings.", evaluation: "Accuracy in identifying valid clues and adherence to system usage guidelines.", duration: null },
      { roundNumber: 2, name: "Physical & Advanced Clue Hunt", format: "Teams explore authorized physical locations and solve advanced challenges to progress through levels.", evaluation: "Team that successfully completes all levels in the shortest time wins.", duration: null },
    ],
    criteria: [],
  },
  {
    title: "Mad Ad",
    japaneseName: "Tokyo Ad Wars",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415738/21.jpg_vskzw0.jpg",
    category: "Technical",
    overview: "A creative team-based video production competition where participants create an original promotional video based on a theme revealed during the event.",
    day: 2,
    time: "10:30AM - 11:30AM",
    venue: "401",
    rules: [
      "Open to all undergraduate students of the institution.",
      "Team Consist of 3-4 members",
     "All members of the team should individually register for the event" ,
      "Participants must bring their own mobile phone or laptop with required editing software installed.",
      "The theme/product will be revealed only during the event.",
      "All content must be original and created during the competition time.",
      "No copyrighted or inappropriate content is allowed.",
      "Internet access is allowed only for royalty-free music or assets.",
      "Late submissions will not be accepted.",
      "Judges' decision will be final and binding.",
    ],
    rounds: [
      { roundNumber: 1, name: "Concept & Planning", format: "Participants receive the theme/product and prepare a storyboard or conceptual plan.", evaluation: "Creativity, clarity of concept, and feasibility of execution.", duration: null },
      { roundNumber: 2, name: "Video Creation", format: "Teams shoot and edit the promotional video. Duration: strictly 1–3 minutes.", evaluation: "Originality, storytelling, technical quality and adherence to theme.", duration: "1–3 minutes" },
      { roundNumber: 3, name: "Presentation & Screening", format: "Final videos screened before judges. Each team may give a brief 1-minute explanation.", evaluation: "Overall impact, clarity of presentation and quality of final output.", duration: "1 minute explanation" },
    ],
    criteria: ["Originality", "Storytelling", "Technical quality", "Adherence to theme", "Overall impact"],
  },
  {
    title: "Line Follower",
    japaneseName: "Shinrai Circuit",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415740/23.jpg_jb2jiq.jpg",
    category: "Technical",
    overview: "An autonomous robotics competition where teams design and program a robot to follow a predefined black line track.",
    day: 1,
    time: "10:00 AM",
    venue: "006",
    rules: [
      "Each team must consist of a minimum of 2 and a maximum of 4 participants.",
     "All members of the team should individually register for the event" ,
      "Individual participation is not allowed.",
      "The robot must be fully autonomous; manual control during the run is strictly prohibited.",
      "Touching the robot during the run will result in penalties.",
      "If the robot goes off the track, the team may place it back at the last checkpoint with a time penalty.",
      "The robot must fit within the specified size limits; all power supplies must be onboard.",
      "Teams must report to the venue on time; late entries may be disqualified.",
      "The decision of the judges will be final and binding.",
    ],
    rounds: [],
    criteria: ["Successful track completion", "Time taken", "Adherence to autonomy rules"],
  },
  {
    title: "Circuit Heist",
    japaneseName: "Shinko Circuit",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415740/25.jpg_sty2eb.jpg",
    category: "Technical",
    overview: "A team-based technical competition focused on electronics-based questions.",
    day: 2,
    time: "9:30AM - 11:00AM",
    venue: "EC LAB",
    rules: [
      "Each team must consist of exactly 2 members.",
     "All members of the team should individually register for the event" ,
      "Questions will be based on electronics concepts.",
      "Participants must carry their valid college ID cards.",
      "Teams must report to the venue at least 15 minutes before the event start time.",
      "Late submissions will not be accepted under any circumstances.",
      "Use of mobile phones, smart devices, or internet access is strictly prohibited.",
      "No communication between teams is allowed during the event.",
      "Any form of cheating or malpractice will lead to immediate disqualification.",
      "Judges' decisions will be final and binding.",
    ],
    rounds: [],
    criteria: [],
  },
  {
    title: "Reverse Engineering",
    japaneseName: "Takumi Breakdown",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415743/27.jpg_q6q6ia.jpg",
    category: "Technical",
    overview: "A reverse-engineering based competition where participants analyse and deconstruct a given product to determine how it functions.",
    day: 1,
    time: "10:00 AM",
    venue: "Mechanical Workshop",
    rules: [
      "Participants must work only within their assigned teams; no external collaboration is permitted.",
      "Attacking or attempting to compromise the contest's scoring system is strictly prohibited.",
      "Standard reverse engineering tools (Ghidra, IDA Pro, Binary Ninja, GDB) are generally permitted.",
      "Automated brute-forcing is strictly banned.",
      "Mandatory use of safety gear for all hardware teardown activities.",
      "No refunds will be provided after payment.",
    ],
    rounds: [
      { roundNumber: 1, name: "Observation & Deconstruction", format: "Observe the given product; physically dismantle hardware or use approved software tools.", evaluation: "Systematic observation, correct identification of components and proper deconstruction methodology.", duration: null },
      { roundNumber: 2, name: "Analysis & Logic Extraction", format: "Analyse the identified components to determine the logic and functioning of the system.", evaluation: "Accuracy in identifying the underlying logic, clarity of explanation and technical correctness.", duration: null },
    ],
    criteria: [],
  },
  {
    title: "Memoria",
    japaneseName: "Memoria kai",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415745/29.jpg_q8ijdp.jpg",
    category: "Technical",
    overview: "A memory and observation-based team competition where participants must view images and names displayed for a limited time and accurately reproduce them.",
    day: 1,
    time: "2:30PM - 3:30PM",
    venue: "301",
    rules: [
      "The event is conducted strictly in teams of 2 members only.",
     "All members of the team should individually register for the event" ,
      "Writing is permitted only after the display ends.",
      "Answers must match the exact spelling as shown on the slide.",
      "Participants must maintain complete silence during all rounds.",
      "No electronic gadgets are allowed.",
      "Any discussion with other teams or use of unfair means will lead to immediate disqualification.",
      "The decision of the judges and organizing committee will be final and binding.",
    ],
    rounds: [
      { roundNumber: 1, name: "Visual Display Round", format: "Images and names will be displayed on the screen for a limited duration.", evaluation: "Accuracy of spelling and completeness of recalled content.", duration: null },
      { roundNumber: 2, name: "Sequence-Based Round", format: "Participants must recall and write answers in the correct sequence as displayed.", evaluation: "Marks awarded based on correctness and proper order of responses.", duration: null },
    ],
    criteria: ["Accuracy of recall", "Correct spelling", "Proper sequence"],
  },
  {
    title: "Slow Bike Racing",
    japaneseName: "Kame Ride",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415747/31.jpg_r4vmiw.jpg",
    category: "Technical",
    overview: "A skill-based riding event where the rider who takes the longest time to reach the finish line without violating any rules wins.",
    day: 1,
    time: "10:00 AM",
    venue: "PARKING",
    rules: [
      "Helmet is mandatory for all riders. No helmet = no participation.",
      "Riders must stay within the marked lane and must not touch or cross lane boundaries.",
      "Riders must not place their feet on the ground until they reach the finish line.",
      "Any type of two-wheeler is allowed to participate.",
      "The rider who takes the maximum time without breaking rules will be declared the winner.",
      "Any unsafe riding behaviour or rule violation may lead to disqualification.",
      "Judges' and organizers' decisions are final and binding.",
    ],
    rounds: [],
    criteria: ["Maximum time to finish without rule violation", "Balance and control"],
},
{
    title: "Water Rocketry",
    japaneseName: "Tenshi Launch",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415749/33.jpg_xaleev.jpg",
    category: "Technical",
    overview: "A team-based engineering competition where participants design and launch water rockets to compete in distance and target accuracy challenges.",
    day: 1,
    time: "10:00 AM",
    venue: "Ground",
    rules: [
      "Each team can have a maximum of 4 members from the same institution.",
     "All members of the team should individually register for the event",
      "Rockets and launchers must be brought by participants.",
      "Teams must bring their own launch pads and pumps.",
      "Maximum rocket volume: 2.5 litres.",
      "Only water is allowed as the working fluid and propellant.",
      "Electronic components and chemical additives are strictly prohibited.",
      "Multi-stage rockets and parachute/gliding mechanisms are permitted.",
      "Judges' and organizers' decisions are final and binding.",
      "No refunds will be provided after payment.",
    ],
    rounds: [
      { roundNumber: 1, name: "Distance Challenge", format: "Rockets launched for maximum horizontal distance. Score = Distance × Time-of-Flight × 0.02", evaluation: "Teams ranked by calculated score.", duration: null },
      { roundNumber: 2, name: "Target Accuracy", format: "Aim at target 65m away. Inner (10m): 20pts, Middle (15m): 15pts, Outer (20m): 10pts.", evaluation: "Points awarded based on landing zone.", duration: null },
    ],
    criteria: ["Final Score = Round 1 + Round 2", "Highest total score wins"],
  },
  {
    title: "Nautical Rides",
    japaneseName: "Tokyo Drift",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415752/36.jpg_xmorgx.jpg",
    category: "Non-Technical",
    overview: "A time-based racing game challenge where participants compete individually to cover the maximum distance within a fixed duration while minimizing collisions.",
    day: 1,
    time: "10:00 AM",
    venue: "303",
    rules: [
      "Each player will get 1 minute 30 seconds to play.",
      "Once the round begins, the game cannot be paused or stopped.",
      "The player must choose one car before the round begins and cannot change it during gameplay.",
      "Select either Manual or Automatic mode before the round begins; cannot change during the game.",
      "For every collision, 1 KM will be deducted from the total distance covered.",
      "Final Score = Total Distance Covered - Total Penalty.",
      "Rankings will be decided based on the final recorded score after penalty deductions.",
      "Each participant is allowed one regular attempt.",
      "Participants who wish to improve their score may pay the same registration fee for one additional round; best score counts.",
    ],
    rounds: [],
    criteria: ["Maximum distance covered", "Minimum collisions", "Final Score = Total Distance - Total Penalty"],
  },
  {
    title: "Dumb Charades",
    japaneseName: "Samurai Signals",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415766/38.jpg_icq6wn.jpg",
    category: "Non-Technical",
    overview: "A team-based movie guessing game where participants convey movie names using only actions and gestures.",
    day: 2,
    time: "11:00AM - 12:00PM",
    venue: "406",
    rules: [
      "One team member enacts the movie name using only actions and gestures; the other attempts to guess it.",
      "All members of the team should individually register for the event",
      "Movies will be selected only from English, Kannada and Hindi.",
      "Each team will be timed during their turn.",
      "The team that correctly guesses the movie in the shortest time will be declared the winner.",
      "Only actions and gestures are allowed.",
      "No spoken words, lip movement or sound effects are permitted.",
      "Writing in the air or showing words/letters through gestures is strictly prohibited.",
      "Use of mobile phones is not allowed.",
      "The final decision made by the organizing committee will be binding.",
    ],
    rounds: [],
    criteria: ["Correct movie identified", "Shortest time to guess"],
  },
  {
    title: "VR Flight Landing",
    japaneseName: "Tsubasa Landing",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415758/40.jpg_qc2vzm.jpg",
    category: "Non-Technical",
    overview: "A precision flight simulation challenge where participants must safely land an aircraft within a designated touchdown zone.",
    day: 1,
    time: "10:00 AM",
    venue: "002",
    rules: [
      "The event is primarily solo (individual) participation.",
      "Participants must land the aircraft within the marked touchdown zone on the runway.",
      "The vertical speed must be smooth; hard landings are strictly not allowed.",
      "Participants must maintain proper alignment with the runway, ensure stable control throughout the descent, and bring the aircraft to a complete and safe stop.",
      "Any unsafe or improper aircraft operation may result in immediate disqualification.",
      "Judges' and organizers' decisions will be final and binding in all situations.",
    ],
    rounds: [],
    criteria: ["Accuracy of touchdown zone landing", "Smoothness of descent (vertical speed)", "Runway alignment", "Stable control"],
  },
  {
    title: "BGMI",
    japaneseName: "Bushido Battleground",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415757/42.jpg_lj7a4v.jpg",
    category: "Non-Technical",
    overview: "A team-based mobile gaming tournament where squads compete in an on-site competitive format.",
    day: 1,
    time: "10:15AM - 12:15PM",
    venue: "Auditorium",
    rules: [
      "Team size: 2–4 players per team (Squad/Duo allowed as per tournament format).",
    "All members of the team should individually register for the event", 
      "Once registered, no changes in team members will be allowed during the tournament.",
      "Only mobile phones are allowed for gameplay; emulators, tablets and iPads are strictly prohibited.",
      "All players must be physically present at the venue during their matches.",
      "Teams must join the match room on time; late entries will not be accepted.",
      "Use of cheats, hacks or any unfair means will result in instant disqualification.",
      "Team names must be clean, decent and respectful.",
      "No abuse, toxic behaviour or misconduct will be tolerated.",
      "No refunds will be provided after payment.",
    ],
    rounds: [],
    criteria: [],
  },
  {
    title: "Feast Fiesta(Eating Challenge)",
    japaneseName: "Kawaii Cravings",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415755/44.jpg_zksybb.jpg",
    category: "Non-Technical",
    overview: "A competitive eating challenge where participants compete to consume the maximum quantity of food within a fixed time limit.",
    day: 1,
    time: "11:00AM - 12:30PM",
    venue: "004",
    rules: [
      "The event is primarily individual participation.",
      "Participants must be medically fit and free from conditions that may make competitive eating risky.",
      "Drinking water and napkins will be provided.",
      "Performance-enhancing substances are strictly prohibited.",
      "No tricks to store, hide or manipulate food are allowed.",
      "Vomiting or leaving the table during the challenge may result in disqualification.",
      "Cheating (hiding food, spitting food, etc.) will lead to immediate removal.",
      "Misconduct or unsafe behaviour is strictly prohibited.",
      "Portion sizes and time limits will be decided by the organizers or sponsors.",
    ],
    rounds: [
      { roundNumber: 1, name: "Quick Bite Battle", format: "A soft drink chugging task or a basic speed eating challenge.", evaluation: "Performance based on speed and successful completion.", duration: null },
      { roundNumber: 2, name: "Maximum Munch Mode", format: "A time-based eating round — consume as much food as possible within the allotted time.", evaluation: "Based on total quantity consumed within the official time limit.", duration: null },
    ],
    criteria: ["Maximum quantity of food consumed within the time limit", "Speed and cleanliness (minimal spillage as tie-breaker)"],
  },
  {
    title: "Treasure Hunt",
    japaneseName: "Shogun's Secret Trail",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415760/46.jpg_fc8vwg.jpg",
    category: "Non-Technical",
    overview: "A campus-based treasure hunt where teams solve sequential clues by navigating across designated locations within the college grounds.",
    day: 1,
    time: "1:00PM - 4:00PM",
    venue: "103",
    rules: [
      "Each team must consist minimum of 3 members and maximum upto 5 members.",
     "All members of the team should individually register for the event",
      "No substitutions are allowed once the hunt has officially begun.",
      "Teams must not move, hide or destroy any clue; violation results in immediate disqualification.",
      "Teams must prove they reached each location by photographing the clue or taking a group selfie at the designated spot.",
      "The hunt is strictly limited to the college campus grounds.",
      "Entering off-limits areas is strictly prohibited.",
      "No outsider assistance is allowed.",
      "Teams must respect the campus environment and must not disrupt ongoing classes or activities.",
      "No refunds will be provided after payment.",
    ],
    rounds: [],
    criteria: ["First team to reach the final 'Treasure' location with all clues verified by marshals"],
  },
  {
    title: "Geo-Guesser",
    japaneseName: "Meiro Map",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415762/48.jpg_eoz59z.jpg",
    category: "Non-Technical",
    overview: "A geography-based observation challenge where participants identify real-world locations using visual clues from random street-level images.",
    day: 2,
    time: "9:30AM - 10:30AM",
    venue: "AI&DS LAB",
    rules: [
      "The game will be conducted on a designated website provided by the organizers.",
      "The event consists of five rounds.",
      "In each round, a random Google Street View image will be displayed.",
      "Participants must pin the exact location based on visual observation of the image.",
      "Each round must be completed within the specified time limit.",
      "The event is open for individual participation only.",
      "Use of mobile phones, external devices, apps or any outside assistance is strictly prohibited.",
      "Any form of misconduct or rule violation will lead to immediate disqualification.",
      "No refunds will be provided after payment.",
    ],
    rounds: [],
    criteria: ["Accuracy of location pin (proximity to actual location)", "Total cumulative score across 5 rounds"],
  },
  {
    title: "Free Fire",
    japaneseName: "Samurai Survival",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415765/50.jpg_gcemrl.jpg",
    category: "Non-Technical",
    overview: "A competitive Battle Royale tournament where squads compete against each other to be the last team standing.",
    day: 1,
    time: "10:15AM - 12:15PM",
    venue: "401 & 402",
    rules: [
      "Each team must consist of exactly 4 players.",
      "All members of the team should individually register for the event",
      "No substitutions are allowed once the match has started.",
      "All team members must be present in the lobby at the designated start time.",
      "Maps will be randomly selected from Bermuda, Kalahari or Purgatory.",
      "Use of hacks, scripts or any third-party panels inside the game is strictly prohibited.",
      "Any team found using unfair means will be immediately disqualified without refund or reward.",
      "Players are responsible for their own device performance and internet stability.",
      "Matches will not be restarted due to individual lag or connectivity issues.",
      "No refunds will be provided after payment.",
    ],
    rounds: [],
    criteria: ["Last team standing", "Placement points", "Kill points"],
  },
  {
    title: "Anime Quiz",
    japaneseName: "Sakura Saga Quiz",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415766/52.jpg_r8dsdm.jpg",
    category: "Non-Technical",
    overview: "An anime-themed quiz competition where teams compete across multiple rounds to test their knowledge of characters, series, dialogues and scenes.",
    day: 1,
    time: "11:00AM - 1:00PM",
    venue: "SSOSC",
    rules: [
      "Each team must consist of 2 members.",
      "All members of the team should individually register for the event",
      "Only one final answer per question is allowed.",
      "Correct answer within first 5 seconds: 10 points.",
      "Correct answer within the time limit: 5 points.",
      "Wrong answer: Minus 2 points (if negative marking is applied).",
      "No answer: 0 points.",
      "Fastest correct answer may earn bonus points.",
      "Any form of malpractice will lead to immediate disqualification.",
      "Judges' decisions will be final and binding.",
      "In case of a tie, a tie-breaker round will be conducted.",
      "No refunds will be provided after payment.",
    ],
    rounds: [
      { roundNumber: 1, name: "Character Reveal", format: "Blurred or cropped anime character images displayed. Identify the character name and anime series.", evaluation: "Correct identification of character and series.", duration: null },
      { roundNumber: 2, name: "Guess the Anime", format: "A scene or symbol is shown. Identify the anime title.", evaluation: "Correct anime title identification.", duration: null },
      { roundNumber: 3, name: "Dialogue Challenge", format: "A famous anime dialogue is displayed. Guess the character or the anime.", evaluation: "Correct character/anime identification.", duration: null },
      { roundNumber: 4, name: "Rapid Fire (Final Round)", format: "5–10 quick questions with a shorter time limit. Double points in this round.", evaluation: "Speed and accuracy; double points apply.", duration: null },
    ],
    criteria: ["Accuracy per question", "Speed of answer", "Total cumulative score"],
  },
  {
    title: "Super Minute",
    japaneseName: "Hayai Challenge",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415774/54.jpg_qpi9j6.jpg",
    category: "Non-Technical",
    overview: "A fast-paced challenge event where participant must complete assigned tasks within a  60-second time limit.",
    day: 1,
    time: "12:00PM - 1:30PM",
    venue: "407",
    rules: [
      "A participant will be given 60 seconds to complete the assigned task.",
      "The event is open for individual participation only.",
      "The timer will begin immediately after the official signal from the event coordinator.",
      "Participants must strictly follow the instructions provided for each challenge.",
      "Once the challenge begins, participants cannot restart unless permitted by the judges.",
      "In case of a tie, a tie-breaker round will be conducted under the same time constraints.",
      "No external assistance (verbal, physical or digital) is permitted during the challenge.",
      "Any violation of rules or use of unfair means will result in immediate disqualification.",
      "No refunds will be provided after payment.",
    ],
    rounds: [],
    criteria: ["Task completion within 60 seconds", "Accuracy of task execution", "Speed and precision"],
  },
  {
    title: "Reels Making",
    japaneseName: "Tokyo Frames",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415776/56.jpg_fb7xx4.jpg",
    category: "Non-Technical",
    overview: "A creative short-form video competition where individual participants produce an engaging and original reel based on a given theme.",
    day: 1,
    time: "10:00 AM",
    venue: "003",
    rules: [
      "The event is strictly open for individual participation only.",
      "The theme/topic will be revealed at the beginning of the event.",
      "The duration of the reel must be between 30–90 seconds.",
      "All content must be original and created during the competition period.",
      "The reel must be submitted in the specified format and within the given deadline.",
      "Late submissions will not be accepted.",
      "No copyrighted, offensive or inappropriate content is allowed.",
      "Pre-made, previously published or AI-generated content is strictly prohibited.",
      "Participants must bring their own mobile device with required editing software installed.",
      "Any form of malpractice will result in immediate disqualification.",
      "No refunds will be provided after payment.",
    ],
    rounds: [],
    criteria: ["Creativity and originality of the concept", "Relevance to the given theme", "Quality of editing and presentation", "Engagement value and overall impact", "Adherence to time limit and event guidelines"],
  },
]
