export const megaEvents = [
  {
    title: "Dance Battle",
    japaneseName: "Ronin Rhythm",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415730/2.jpg_nn3xcx.jpg",
    category: "Mega",
    overview: "Individual head-to-head dance battles with changing music genres in a knockout format leading to a Final Showdown.",
    day: 1,
    time: "12:30PM - 4:00PM",
    venue: "Badminton Court",
    rules: [
      "Individual participations only.",
      "Each battle features two dancers facing off in a head-to-head challenge.",
      "Battle Format: Each round, the music genre changes unpredictably. Possible styles include Rap, Pop, Break beats, Funk, Electronica, House, Bollywood etc.",
      "Time per dancer: 45–60 seconds to showcase their moves before the opponent responds.",
      "Battles are conducted in a knockout format, leading to a Final Showdown.",
      "Judges select one dancer from each battle to advance to the next round.",
      "The knockout rounds continue until only two dancers remain for the final showdown.",
      "Final Showdown: The last two dancers compete in multiple rounds with surprise music transitions.",
    ],
    rounds: [],
    criteria: ["Artistic Creativity", "Musicality & Rhythm Adaptation", "Stage Presence & Confidence", "Crowd Engagement", "Overall Entertainment Value"],
  },
  {
    title: "Group Dance",
    japaneseName: "Odori Matsuri",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415730/4.jpg_eynb1h.jpg",
    category: "Mega",
    overview: "Team-based dance performance event showcasing creativity and versatility in Eastern and Western styles.",
    day: 2,
    time: "11:30AM - 1:30PM",
    venue: "Auditorium",
    rules: [
      "Teams must consist of a minimum of 4 and a maximum of 15 members.", "All members of the team should individually register for the event" ,
      "Performance duration: 5+2 minutes (including stage setup and clearance).",
      "Dance styles encompass both Eastern and Western forms without separate categories.",
      "Teams must showcase their creativity and versatility within the given time frame.",
      "Use of props is allowed but should not cause stage damage.",
      "Any form of inappropriate content or offensive gestures will lead to disqualification.",
    ],
    rounds: [],
    criteria: ["Expressions", "Choreography", "Synchronization & Impact", "Costumes"],
  },
  {
    title: "Mr or Ms Envision",
    japaneseName: "Mr or Ms Sakura Crown",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415732/6.jpg_e5csnj.jpg",
    category: "Mega",
    overview: "Individual personality competition testing aptitude, public speaking and composure under stress.",
    day: 1,
    time: "1:00PM - 2:00PM",
    venue: "003",
    rules: [
      "Individual participations only.",
      "Teams must report 30 minutes before their performance.",
      "Exceeding time limits may result in point deduction.",
    ],
    rounds: [
      { roundNumber: 1, name: "Aptitude Test", format: "Written test on logical reasoning, analytical skills, basic problem-solving.", evaluation: "Top performers qualify for Round 2.", duration: "30 minutes" },
      { roundNumber: 2, name: "Effective Public Speaking", format: "Spontaneous topic given on the spot; must deliver a structured speech without prior preparation.", evaluation: "Clarity and fluency, Confidence and stage presence, Relevance and strength of content.", duration: "2 minutes per participant" },
      { roundNumber: 3, name: "Stress Interview", format: "Participants dress as a chosen character; judges ask situational and character-based questions.", evaluation: "Creativity and spontaneity, Presence of mind, Ability to handle stress effectively.", duration: "5–7 minutes per participant" },
    ],
    criteria: ["Aptitude Test: Problem-solving ability and logical reasoning", "Public Speaking: Clarity, fluency and confidence", "Stress Interview: Creativity, presence of mind and ability to handle pressure"],
  },
  {
    title: "Singing",
    japaneseName: "Samurai Symphony",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415732/8.jpg_vcetxc.jpg",
    category: "Mega",
    overview: "A multi-round singing competition open to individual participants, evaluating voice quality, expression and style.",
    day: 2,
    time: "10:00AM - 12:00PM",
    venue: "Main Stage",
    rules: [
      "All registered participants are eligible to perform in Round 1.",
      "Individual participations only.",
      "Participants can sing any song of their choice in any language in Round 1.",
      "Karaoke track is allowed, but singing without a track is also permitted.",
      "Participants must report 30 minutes before their performance.",
      "Exceeding time limits may result in point deduction.",
    ],
    rounds: [
      { roundNumber: 1, name: "Open Singing Round", format: "Theme: Free Choice. Any song in any language. Karaoke allowed.", evaluation: "Voice quality, pitch, rhythm and stage confidence.", duration: "3+1 minutes per participant" },
      { roundNumber: 2, name: "Expression Round", format: "Theme: Emotion & Style. Song must express emotion; facial expressions and gestures allowed.", evaluation: "Expression, creativity and overall performance style.", duration: "2+1 minutes" },
    ],
    criteria: ["Voice quality", "Pitch and rhythm", "Stage confidence", "Expression and creativity"],
  },
  {
    title: "Cricket",
    japaneseName: "Dojo Dominators",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415732/10.jpg_l5wwnq.jpg",
    category: "Mega",
    overview: "Knockout format cricket tournament with 8-player teams and short 2–3 over matches.",
    day: 1,
    time: "10:00 AM",
    venue: "Ground",
    rules: [
      "Match Format: Knockout matches : 2–3 overs per side depending on registration.",
      "All members of the team should individually register for the event" ,
      "Each team shall consist of 8 players.",
      "Overs & Bowling Rule (1-1-1): Each bowler can bowl only 1 over.",
      "All 8 players can bat. If 7 wickets fall, last batter may not continue.",
      "Boundary will be marked within 30 yards.",
      "Wide and No-ball will give 1 extra run + extra ball.",
      "The umpire's decision is final and binding.",
      "In case of tie: Super Over (1 over each); Higher boundary count if Super Over not possible.",
      "Misconduct or arguments with umpire may lead to disqualification.",
    ],
    rounds: [],
    criteria: [],
  },
];
