export const nonTechEvents = [
  {
    title: "Nautical Rides",
    japaneseName: "Tokyo Drift",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415752/36.jpg_xmorgx.jpg",
    category: "Non-Technical",
    overview: "A time-based racing game challenge where participants compete individually to cover the maximum distance within a fixed duration while minimizing collisions.",
    day: 1,
    time: "10:00 AM",
    venue: "303",
    rules: [
      "Each player will get 1 minute 30 seconds to play.",
      "Once the round begins, the game cannot be paused or stopped.",
      "The player must choose one car before the round begins and cannot change it during gameplay.",
      "Select either Manual or Automatic mode before the round begins; cannot change during the game.",
      "For every collision, 1 KM will be deducted from the total distance covered.",
      "Final Score = Total Distance Covered - Total Penalty.",
      "Rankings will be decided based on the final recorded score after penalty deductions.",
      "Each participant is allowed one regular attempt.",
      "Participants who wish to improve their score may pay the same registration fee for one additional round; best score counts.",
    ],
    rounds: [],
    criteria: ["Maximum distance covered", "Minimum collisions", "Final Score = Total Distance - Total Penalty"],
  },
  {
    title: "Dumb Charades",
    japaneseName: "Samurai Signals",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415766/38.jpg_icq6wn.jpg",
    category: "Non-Technical",
    overview: "A team-based movie guessing game where participants convey movie names using only actions and gestures.",
    day: 2,
    time: "11:00AM - 12:00PM",
    venue: "406",
    rules: [
      "One team member enacts the movie name using only actions and gestures; the other attempts to guess it.",
      "All members of the team should individually register for the event",
      "Movies will be selected only from English, Kannada and Hindi.",
      "Each team will be timed during their turn.",
      "The team that correctly guesses the movie in the shortest time will be declared the winner.",
      "Only actions and gestures are allowed.",
      "No spoken words, lip movement or sound effects are permitted.",
      "Writing in the air or showing words/letters through gestures is strictly prohibited.",
      "Use of mobile phones is not allowed.",
      "The final decision made by the organizing committee will be binding.",
    ],
    rounds: [],
    criteria: ["Correct movie identified", "Shortest time to guess"],
  },
  {
    title: "VR Flight Landing",
    japaneseName: "Tsubasa Landing",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415758/40.jpg_qc2vzm.jpg",
    category: "Non-Technical",
    overview: "A precision flight simulation challenge where participants must safely land an aircraft within a designated touchdown zone.",
    day: 1,
    time: "10:00 AM",
    venue: "002",
    rules: [
      "The event is primarily solo (individual) participation.",
      "Participants must land the aircraft within the marked touchdown zone on the runway.",
      "The vertical speed must be smooth; hard landings are strictly not allowed.",
      "Participants must maintain proper alignment with the runway, ensure stable control throughout the descent, and bring the aircraft to a complete and safe stop.",
      "Any unsafe or improper aircraft operation may result in immediate disqualification.",
      "Judges' and organizers' decisions will be final and binding in all situations.",
    ],
    rounds: [],
    criteria: ["Accuracy of touchdown zone landing", "Smoothness of descent (vertical speed)", "Runway alignment", "Stable control"],
  },
  {
    title: "BGMI",
    japaneseName: "Bushido Battleground",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415757/42.jpg_lj7a4v.jpg",
    category: "Non-Technical",
    overview: "A team-based mobile gaming tournament where squads compete in an on-site competitive format.",
    day: 1,
    time: "10:15AM - 12:15PM",
    venue: "Auditorium",
    rules: [
      "Team size: 2–4 players per team (Squad/Duo allowed as per tournament format).",
    "All members of the team should individually register for the event", 
      "Once registered, no changes in team members will be allowed during the tournament.",
      "Only mobile phones are allowed for gameplay; emulators, tablets and iPads are strictly prohibited.",
      "All players must be physically present at the venue during their matches.",
      "Teams must join the match room on time; late entries will not be accepted.",
      "Use of cheats, hacks or any unfair means will result in instant disqualification.",
      "Team names must be clean, decent and respectful.",
      "No abuse, toxic behaviour or misconduct will be tolerated.",
      "No refunds will be provided after payment.",
    ],
    rounds: [],
    criteria: [],
  },
  {
    title: "Hogathon",
    japaneseName: "Kawaii Cravings",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415755/44.jpg_zksybb.jpg",
    category: "Non-Technical",
    overview: "A competitive eating challenge where participants compete to consume the maximum quantity of food within a fixed time limit.",
    day: 1,
    time: "11:00AM - 12:30PM",
    venue: "004",
    rules: [
      "The event is primarily individual participation.",
      "Participants must be medically fit and free from conditions that may make competitive eating risky.",
      "Drinking water and napkins will be provided.",
      "Performance-enhancing substances are strictly prohibited.",
      "No tricks to store, hide or manipulate food are allowed.",
      "Vomiting or leaving the table during the challenge may result in disqualification.",
      "Cheating (hiding food, spitting food, etc.) will lead to immediate removal.",
      "Misconduct or unsafe behaviour is strictly prohibited.",
      "Portion sizes and time limits will be decided by the organizers or sponsors.",
    ],
    rounds: [
      { roundNumber: 1, name: "Quick Bite Battle", format: "A soft drink chugging task or a basic speed eating challenge.", evaluation: "Performance based on speed and successful completion.", duration: null },
      { roundNumber: 2, name: "Maximum Munch Mode", format: "A time-based eating round — consume as much food as possible within the allotted time.", evaluation: "Based on total quantity consumed within the official time limit.", duration: null },
    ],
    criteria: ["Maximum quantity of food consumed within the time limit", "Speed and cleanliness (minimal spillage as tie-breaker)"],
  },
  {
    title: "Treasure Hunt",
    japaneseName: "Shogun's Secret Trail",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415760/46.jpg_fc8vwg.jpg",
    category: "Non-Technical",
    overview: "A campus-based treasure hunt where teams solve sequential clues by navigating across designated locations within the college grounds.",
    day: 1,
    time: "1:00PM - 4:00PM",
    venue: "103",
    rules: [
      "Each team must consist minimum of 3 members and maximum upto 5 members.",
     "All members of the team should individually register for the event",
      "No substitutions are allowed once the hunt has officially begun.",
      "Teams must not move, hide or destroy any clue; violation results in immediate disqualification.",
      "Teams must prove they reached each location by photographing the clue or taking a group selfie at the designated spot.",
      "The hunt is strictly limited to the college campus grounds.",
      "Entering off-limits areas is strictly prohibited.",
      "No outsider assistance is allowed.",
      "Teams must respect the campus environment and must not disrupt ongoing classes or activities.",
      "No refunds will be provided after payment.",
    ],
    rounds: [],
    criteria: ["First team to reach the final 'Treasure' location with all clues verified by marshals"],
  },
  {
    title: "Geo-Guesser",
    japaneseName: "Meiro Map",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415762/48.jpg_eoz59z.jpg",
    category: "Non-Technical",
    overview: "A geography-based observation challenge where participants identify real-world locations using visual clues from random street-level images.",
    day: 2,
    time: "9:30AM - 10:30AM",
    venue: "AIDS LAB",
    rules: [
      "The game will be conducted on a designated website provided by the organizers.",
      "The event consists of five rounds.",
      "In each round, a random Google Street View image will be displayed.",
      "Participants must pin the exact location based on visual observation of the image.",
      "Each round must be completed within the specified time limit.",
      "The event is open for individual participation only.",
      "Use of mobile phones, external devices, apps or any outside assistance is strictly prohibited.",
      "Any form of misconduct or rule violation will lead to immediate disqualification.",
      "No refunds will be provided after payment.",
    ],
    rounds: [],
    criteria: ["Accuracy of location pin (proximity to actual location)", "Total cumulative score across 5 rounds"],
  },
  {
    title: "Free Fire",
    japaneseName: "Samurai Survival",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415765/50.jpg_gcemrl.jpg",
    category: "Non-Technical",
    overview: "A competitive Battle Royale tournament where squads compete against each other to be the last team standing.",
    day: 1,
    time: "10:15AM - 12:15PM",
    venue: "401 & 402",
    rules: [
      "Each team must consist of exactly 4 players.",
      "All members of the team should individually register for the event",
      "No substitutions are allowed once the match has started.",
      "All team members must be present in the lobby at the designated start time.",
      "Maps will be randomly selected from Bermuda, Kalahari or Purgatory.",
      "Use of hacks, scripts or any third-party panels inside the game is strictly prohibited.",
      "Any team found using unfair means will be immediately disqualified without refund or reward.",
      "Players are responsible for their own device performance and internet stability.",
      "Matches will not be restarted due to individual lag or connectivity issues.",
      "No refunds will be provided after payment.",
    ],
    rounds: [],
    criteria: ["Last team standing", "Placement points", "Kill points"],
  },
  {
    title: "Anime Quiz",
    japaneseName: "Sakura Saga Quiz",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415766/52.jpg_r8dsdm.jpg",
    category: "Non-Technical",
    overview: "An anime-themed quiz competition where teams compete across multiple rounds to test their knowledge of characters, series, dialogues and scenes.",
    day: 1,
    time: "11:00AM - 1:00PM",
    venue: "SSOSC",
    rules: [
      "Each team must consist of 2 members.",
      "All members of the team should individually register for the event",
      "Only one final answer per question is allowed.",
      "Correct answer within first 5 seconds: 10 points.",
      "Correct answer within the time limit: 5 points.",
      "Wrong answer: Minus 2 points (if negative marking is applied).",
      "No answer: 0 points.",
      "Fastest correct answer may earn bonus points.",
      "Any form of malpractice will lead to immediate disqualification.",
      "Judges' decisions will be final and binding.",
      "In case of a tie, a tie-breaker round will be conducted.",
      "No refunds will be provided after payment.",
    ],
    rounds: [
      { roundNumber: 1, name: "Character Reveal", format: "Blurred or cropped anime character images displayed. Identify the character name and anime series.", evaluation: "Correct identification of character and series.", duration: null },
      { roundNumber: 2, name: "Guess the Anime", format: "A scene or symbol is shown. Identify the anime title.", evaluation: "Correct anime title identification.", duration: null },
      { roundNumber: 3, name: "Dialogue Challenge", format: "A famous anime dialogue is displayed. Guess the character or the anime.", evaluation: "Correct character/anime identification.", duration: null },
      { roundNumber: 4, name: "Rapid Fire (Final Round)", format: "5–10 quick questions with a shorter time limit. Double points in this round.", evaluation: "Speed and accuracy; double points apply.", duration: null },
    ],
    criteria: ["Accuracy per question", "Speed of answer", "Total cumulative score"],
  },
  {
    title: "Super Minute",
    japaneseName: "Hayai Challenge",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415774/54.jpg_qpi9j6.jpg",
    category: "Non-Technical",
    overview: "A fast-paced challenge event where participant must complete assigned tasks within a  60-second time limit.",
    day: 1,
    time: "12:00PM - 1:30PM",
    venue: "407",
    rules: [
      "A participant will be given 60 seconds to complete the assigned task.",
      "The event is open for individual participation only.",
      "The timer will begin immediately after the official signal from the event coordinator.",
      "Participants must strictly follow the instructions provided for each challenge.",
      "Once the challenge begins, participants cannot restart unless permitted by the judges.",
      "In case of a tie, a tie-breaker round will be conducted under the same time constraints.",
      "No external assistance (verbal, physical or digital) is permitted during the challenge.",
      "Any violation of rules or use of unfair means will result in immediate disqualification.",
      "No refunds will be provided after payment.",
    ],
    rounds: [],
    criteria: ["Task completion within 60 seconds", "Accuracy of task execution", "Speed and precision"],
  },
  {
    title: "Reels Making",
    japaneseName: "Tokyo Frames",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415776/56.jpg_fb7xx4.jpg",
    category: "Non-Technical",
    overview: "A creative short-form video competition where individual participants produce an engaging and original reel based on a given theme.",
    day: 1,
    time: "10:00 AM",
    venue: "003",
    rules: [
      "The event is strictly open for individual participation only.",
      "The theme/topic will be revealed at the beginning of the event.",
      "The duration of the reel must be between 30–90 seconds.",
      "All content must be original and created during the competition period.",
      "The reel must be submitted in the specified format and within the given deadline.",
      "Late submissions will not be accepted.",
      "No copyrighted, offensive or inappropriate content is allowed.",
      "Pre-made, previously published or AI-generated content is strictly prohibited.",
      "Participants must bring their own mobile device with required editing software installed.",
      "Any form of malpractice will result in immediate disqualification.",
      "No refunds will be provided after payment.",
    ],
    rounds: [],
    criteria: ["Creativity and originality of the concept", "Relevance to the given theme", "Quality of editing and presentation", "Engagement value and overall impact", "Adherence to time limit and event guidelines"],
  },
];
