export const techEvents = [
  {
    title: "Rahasya",
    japaneseName: "Kage Investigation",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415734/13.jpg_l1bvny.jpg",
    category: "Technical",
    overview: "A team-based competitive investigation event testing teamwork, analytical skills, and adherence to competition guidelines.",
    day: 2,
    time: "9:30AM - 11:00 AM",
    venue: "AIML LAB",
    rules: [
      "Participation is strictly in teams of 3–4 members.",
      "All members of the team should individually register for the event" ,
      "Each team is allowed to use only one laptop or desktop.",
      "Total Duration: 2 Hours 20 Minutes (Briefing: 15 min, Investigation Rounds: 1 hr 45 min, Extra Time: 20 min).",
      "No external internet usage is allowed unless explicitly permitted by the organizers.",
      "Only approved tools and software may be used during the event.",
      "Tampering with event materials or setup is strictly prohibited.",
      "No communication between teams is allowed during the competition.",
      "Any form of misconduct will result in immediate disqualification.",
      "The decision of the organizers will be final and binding.",
    ],
    rounds: [],
    criteria: [],
  },
  {
    title: "Blind Coding",
    japaneseName: "Kizuna Code",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415734/15.jpg_mrjd9y.jpg",
    category: "Technical",
    overview: "A collaborative coding challenge where one participant writes code while the other guides verbally without visual access to the screen.",
    day: 1,
    time: "2:00PM - 3:00PM",
    venue: "AIDS lab",
    rules: [
      "Participation is strictly in teams of 2 members",
      "All members of the team should individually register for the event" ,
      "Players will sit opposite each other during the competition.",
      "One player acts as the Coder (sees screen and types); the other is the Guide (dictates logic without seeing the screen).",
      "The Guide must not touch the keyboard, mouse or screen at any time.",
      "No gestures, signs, written notes or non-verbal assistance are allowed.",
      "The programming language will be announced before the event begins.",
      "Code must be written strictly according to the given problem statement.",
      "Any violation of rules will result in immediate disqualification.",
    ],
    rounds: [],
    criteria: ["Correctness of the code", "Adherence to instructions", "Successful execution within the time limit"],
  },
  {
    title: "Reverse Coding",
    japaneseName: "Shinobi Syntax",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415733/17.jpg_mjezez.jpg",
    category: "Technical",
    overview: "A technical coding competition where participants analyse a given output and reconstruct the logic to match it.",
    day: 2,
    time: "11:00AM - 12:00PM",
    venue: "ISE LAB",
    rules: [
      "Participants may register individually or in a team of maximum 2 members.",
      "Both rounds will strictly follow the Reverse Coding format.",
      "Internet access is strictly prohibited during the competition.",
      "Use of mobile phones, AI tools, online resources or external assistance is not allowed.",
      "Any form of malpractice will lead to immediate disqualification.",
      "No refunds will be provided after payment.",
    ],
    rounds: [
      { roundNumber: 1, name: "Reverse Coding – C Programming", format: "Analyse the provided output and implement the logic strictly using C.", evaluation: "Exact output match including formatting, spacing and structure.", duration: null },
      { roundNumber: 2, name: "Reverse Coding – Python Programming", format: "Analyse the provided output and implement the logic strictly using Python.", evaluation: "Exact output match including formatting, spacing and structure.", duration: null },
    ],
    criteria: [],
  },
  {
    title: "Operation Cipher Chase",
    japaneseName: "Cipher Shinobi",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415734/19.jpg_hep6q3.jpg",
    category: "Technical",
    overview: "A team-based technical treasure hunt where participants solve multi-level challenges by identifying hidden clues within a system and at designated physical locations.",
    day: 2,
    time: "10:30AM - 11:30AM",
    venue: "CS LAB",
    rules: [
      "The event will be conducted in teams of 2–3 participants.",
     "All members of the team should individually register for the event" ,
      "Participants must explore only authorized areas.",
      "Internet access and external devices are strictly prohibited unless permitted by the organizers.",
      "Participants must not alter system settings, delete files, or access restricted system areas.",
      "Any form of unfair means or clue sharing between teams will lead to immediate disqualification.",
      "No refunds will be provided after payment.",
    ],
    rounds: [
      { roundNumber: 1, name: "System Exploration", format: "Teams analyse the provided system to locate hidden digital clues without altering system settings.", evaluation: "Accuracy in identifying valid clues and adherence to system usage guidelines.", duration: null },
      { roundNumber: 2, name: "Physical & Advanced Clue Hunt", format: "Teams explore authorized physical locations and solve advanced challenges to progress through levels.", evaluation: "Team that successfully completes all levels in the shortest time wins.", duration: null },
    ],
    criteria: [],
  },
  {
    title: "Mad Ad",
    japaneseName: "Tokyo Ad Wars",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415738/21.jpg_vskzw0.jpg",
    category: "Technical",
    overview: "A creative team-based video production competition where participants create an original promotional video based on a theme revealed during the event.",
    day: 2,
    time: "10:30AM - 11:30AM",
    venue: "401",
    rules: [
      "Open to all undergraduate students of the institution.",
      "Team Consist of 3-4 members",
     "All members of the team should individually register for the event" ,
      "Participants must bring their own mobile phone or laptop with required editing software installed.",
      "The theme/product will be revealed only during the event.",
      "All content must be original and created during the competition time.",
      "No copyrighted or inappropriate content is allowed.",
      "Internet access is allowed only for royalty-free music or assets.",
      "Late submissions will not be accepted.",
      "Judges' decision will be final and binding.",
    ],
    rounds: [
      { roundNumber: 1, name: "Concept & Planning", format: "Participants receive the theme/product and prepare a storyboard or conceptual plan.", evaluation: "Creativity, clarity of concept, and feasibility of execution.", duration: null },
      { roundNumber: 2, name: "Video Creation", format: "Teams shoot and edit the promotional video. Duration: strictly 1–3 minutes.", evaluation: "Originality, storytelling, technical quality and adherence to theme.", duration: "1–3 minutes" },
      { roundNumber: 3, name: "Presentation & Screening", format: "Final videos screened before judges. Each team may give a brief 1-minute explanation.", evaluation: "Overall impact, clarity of presentation and quality of final output.", duration: "1 minute explanation" },
    ],
    criteria: ["Originality", "Storytelling", "Technical quality", "Adherence to theme", "Overall impact"],
  },
  {
    title: "Line Follower",
    japaneseName: "Shinrai Circuit",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415740/23.jpg_jb2jiq.jpg",
    category: "Technical",
    overview: "An autonomous robotics competition where teams design and program a robot to follow a predefined black line track.",
    day: 1,
    time: "10:00 AM",
    venue: "006",
    rules: [
      "Each team must consist of a minimum of 2 and a maximum of 4 participants.",
     "All members of the team should individually register for the event" ,
      "Individual participation is not allowed.",
      "The robot must be fully autonomous; manual control during the run is strictly prohibited.",
      "Touching the robot during the run will result in penalties.",
      "If the robot goes off the track, the team may place it back at the last checkpoint with a time penalty.",
      "The robot must fit within the specified size limits; all power supplies must be onboard.",
      "Teams must report to the venue on time; late entries may be disqualified.",
      "The decision of the judges will be final and binding.",
    ],
    rounds: [],
    criteria: ["Successful track completion", "Time taken", "Adherence to autonomy rules"],
  },
  {
    title: "Circuit Heist",
    japaneseName: "Shinko Circuit",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415740/25.jpg_sty2eb.jpg",
    category: "Technical",
    overview: "A team-based technical competition focused on electronics-based questions.",
    day: 2,
    time: "9:30AM - 11:00AM",
    venue: "EC LAB",
    rules: [
      "Each team must consist of exactly 2 members.",
     "All members of the team should individually register for the event" ,
      "Questions will be based on electronics concepts.",
      "Participants must carry their valid college ID cards.",
      "Teams must report to the venue at least 15 minutes before the event start time.",
      "Late submissions will not be accepted under any circumstances.",
      "Use of mobile phones, smart devices, or internet access is strictly prohibited.",
      "No communication between teams is allowed during the event.",
      "Any form of cheating or malpractice will lead to immediate disqualification.",
      "Judges' decisions will be final and binding.",
    ],
    rounds: [],
    criteria: [],
  },
  {
    title: "Reverse Engineering",
    japaneseName: "Takumi Breakdown",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415743/27.jpg_q6q6ia.jpg",
    category: "Technical",
    overview: "A reverse-engineering based competition where participants analyse and deconstruct a given product to determine how it functions.",
    day: 1,
    time: "10:00 AM",
    venue: "Mechanical Workshop",
    rules: [
      "Participants must work only within their assigned teams; no external collaboration is permitted.",
      "Attacking or attempting to compromise the contest's scoring system is strictly prohibited.",
      "Standard reverse engineering tools (Ghidra, IDA Pro, Binary Ninja, GDB) are generally permitted.",
      "Automated brute-forcing is strictly banned.",
      "Mandatory use of safety gear for all hardware teardown activities.",
      "No refunds will be provided after payment.",
    ],
    rounds: [
      { roundNumber: 1, name: "Observation & Deconstruction", format: "Observe the given product; physically dismantle hardware or use approved software tools.", evaluation: "Systematic observation, correct identification of components and proper deconstruction methodology.", duration: null },
      { roundNumber: 2, name: "Analysis & Logic Extraction", format: "Analyse the identified components to determine the logic and functioning of the system.", evaluation: "Accuracy in identifying the underlying logic, clarity of explanation and technical correctness.", duration: null },
    ],
    criteria: [],
  },
  {
    title: "Memoria",
    japaneseName: "Memoria kai",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415745/29.jpg_q8ijdp.jpg",
    category: "Technical",
    overview: "A memory and observation-based team competition where participants must view images and names displayed for a limited time and accurately reproduce them.",
    day: 1,
    time: "2:30PM - 3:30PM",
    venue: "301",
    rules: [
      "The event is conducted strictly in teams of 2 members only.",
     "All members of the team should individually register for the event" ,
      "Writing is permitted only after the display ends.",
      "Answers must match the exact spelling as shown on the slide.",
      "Participants must maintain complete silence during all rounds.",
      "No electronic gadgets are allowed.",
      "Any discussion with other teams or use of unfair means will lead to immediate disqualification.",
      "The decision of the judges and organizing committee will be final and binding.",
    ],
    rounds: [
      { roundNumber: 1, name: "Visual Display Round", format: "Images and names will be displayed on the screen for a limited duration.", evaluation: "Accuracy of spelling and completeness of recalled content.", duration: null },
      { roundNumber: 2, name: "Sequence-Based Round", format: "Participants must recall and write answers in the correct sequence as displayed.", evaluation: "Marks awarded based on correctness and proper order of responses.", duration: null },
    ],
    criteria: ["Accuracy of recall", "Correct spelling", "Proper sequence"],
  },
  {
    title: "Slow Bike Racing",
    japaneseName: "Kame Ride",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415747/31.jpg_r4vmiw.jpg",
    category: "Technical",
    overview: "A skill-based riding event where the rider who takes the longest time to reach the finish line without violating any rules wins.",
    day: 1,
    time: "10:00 AM",
    venue: "PARKING",
    rules: [
      "Helmet is mandatory for all riders. No helmet = no participation.",
      "Riders must stay within the marked lane and must not touch or cross lane boundaries.",
      "Riders must not place their feet on the ground until they reach the finish line.",
      "Any type of two-wheeler is allowed to participate.",
      "The rider who takes the maximum time without breaking rules will be declared the winner.",
      "Any unsafe riding behaviour or rule violation may lead to disqualification.",
      "Judges' and organizers' decisions are final and binding.",
    ],
    rounds: [],
    criteria: ["Maximum time to finish without rule violation", "Balance and control"],
  },
  {
    title: "Water Rocketry",
    japaneseName: "Tenshi Launch",
    imageUrl: "https://res.cloudinary.com/dwnvl9k9j/image/upload/v1774415749/33.jpg_xaleev.jpg",
    category: "Technical",
    overview: "A team-based engineering competition where participants design and launch water rockets to compete in distance and target accuracy challenges.",
    day: 1,
    time: "10:00 AM",
    venue: "Ground",
    rules: [
      "Each team can have a maximum of 4 members from the same institution.",
     "All members of the team should individually register for the event",
      "Rockets and launchers must be brought by participants.",
      "Teams must bring their own launch pads and pumps.",
      "Maximum rocket volume: 2.5 litres.",
      "Only water is allowed as the working fluid and propellant.",
      "Electronic components and chemical additives are strictly prohibited.",
      "Multi-stage rockets and parachute/gliding mechanisms are permitted.",
      "Judges' and organizers' decisions are final and binding.",
      "No refunds will be provided after payment.",
    ],
    rounds: [
      { roundNumber: 1, name: "Distance Challenge", format: "Rockets launched for maximum horizontal distance. Score = Distance × Time-of-Flight × 0.02", evaluation: "Teams ranked by calculated score.", duration: null },
      { roundNumber: 2, name: "Target Accuracy", format: "Aim at target 65m away. Inner (10m): 20pts, Middle (15m): 15pts, Outer (20m): 10pts.", evaluation: "Points awarded based on landing zone.", duration: null },
    ],
    criteria: ["Final Score = Round 1 + Round 2", "Highest total score wins"],
  },
];
